version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping the Lambda function"
      - zip -r lambda-function.zip .  # Zip the Python Lambda function for deployment

artifacts:
  files:
    - lambda-function.zip

